name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: npm install

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Run client tests
        working-directory: client
        run: npm test --if-present

      - name: Run server tests
        run: npm test server.test.js --if-present  # Make sure to run server-side tests

