name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:    
        node-version: [22.x] # Only test on Node.js 22 and later

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: yarn install

      - name: Install client dependencies
        working-directory: client
        run: yarn install

      - name: Install dependencies (server)
        working-directory: server
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Run server tests
        working-directory: server
        run: yarn test  
      

